apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: microservice-opa-integration
servers: 1
agents: 2
registries:
  config: |
    mirrors:
      "localhost:5000":
        endpoint:
          - "http://custom-registry:5000"
network: ${DOCKER_NETWORK}
ports:
  - port: 8080:80  # For NGINX ingress 
    nodeFilters:
      - loadbalancer
  - port: 30080:30080 
    nodeFilters:
      - agent:* 
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
          - server:*