services:
  authz-service:
    profiles: ["authz"]
    hostname: authz-service
    container_name: authz-service
    image: openpolicyagent/opa:latest
    command: ["run", "--server", "--addr", "0.0.0.0:8181", "/policies"]
    volumes:
      - $PWD/policies:/policies
    ports:
      - "127.0.0.1:8181:8181"
    networks:
      - app

  simple-microservice:
    profiles: ["app"]
    hostname: simple-opa-integration
    container_name: simple-opa-integration
    image: simple-opa-integration:latest
    environment:
      - AUTHZ_SERVER_HOST=authz-service
      - AUTHZ_SERVER_PORT=8181
      - WEB_SERVER_HOST=0.0.0.0
      - WEB_SERVER_PORT=8080
    volumes:
      - $PWD/config:/app/config
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app

networks:
  app:
    external: true
    name: app