services:
  authz-service-v1:
    profiles: ["authz-v1"]
    hostname: authz-service
    container_name: authz-service-v1
    image: openpolicyagent/opa:latest
    command:
      - run
      - --server
      - --addr
      - 0.0.0.0:8181
      - --log-level
      - debug
      - --set=decision_logs.console=true
      - /policies
    volumes:
      - $PWD/deployment/authz/policies:/policies
    ports:
      - "127.0.0.1:8181:8181"
    networks:
      - app

  bundle-server:
    profiles: [ "authz-v2" ]
    image: python:3.12-slim
    container_name: bundle-server
    working_dir: /bundle
    command: python3 -m http.server 8888
    volumes:
      - $PWD/deployment/authz/dist:/bundle
    ports:
      - "127.0.0.1:8888:8888"
    networks:
      - app

  authz-service-v2:
    profiles: [ "authz-v2" ]
    hostname: authz-service
    container_name: authz-service-v2
    image: openpolicyagent/opa:latest
    command:
      - run
      - --server
      - --addr
      - 0.0.0.0:8181
      - --log-level
      - debug
      - --config-file
      - /authz/config/authz_config.yaml
    volumes:
      - $PWD/deployment/authz/config:/authz/config
    depends_on:
      - bundle-server
    ports:
      - "127.0.0.1:8181:8181"
    networks:
      - app

  aws-mock-service:
    profiles: [ "authz-v3" ]
    hostname: aws-mock-service
    container_name: aws-mock-service
    image: localstack/localstack:4.5.0-arm64
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-west-1
      - AWS_DEFAULT_REGION=us-west-1
    networks:
      - app

  authz-service-s3:
    profiles: [ "authz-v3" ]
    hostname: authz-service
    container_name: authz-service-s3
    image: openpolicyagent/opa:latest
    command:
      - run
      - --server
      - --addr
      - 0.0.0.0:8181
      - --log-level
      - debug
      - --config-file
      - /authz/config/authz_config.yaml
    volumes:
      - $PWD/deployment/authz/s3:/authz/config
    depends_on:
      - aws-mock-service
    ports:
      - "127.0.0.1:8181:8181"
    networks:
      - app

  restapi-auth-opa-integration-microservice:
    profiles: ["app"]
    hostname: restapi-auth-opa-integration
    container_name: restapi-auth-opa-integration
    image: restapi-auth-opa-integration-microservice:latest
    environment:
      - AUTHZ_SERVER_HOST=authz-service
      - AUTHZ_SERVER_PORT=8181
      - WEB_SERVER_HOST=0.0.0.0
      - WEB_SERVER_PORT=8080
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - app

networks:
  app:
    external: true
    name: app